language: ruby
branches:
  only:
    - master
    - PUP-11
services:
  - postgresql
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database delayed_job_test;' -U postgres
script: bundle exec $COMMAND
env:
  global:
    - COMMAND=rspec
  
rvm: # Supported
  - 2.7.4

jdk: oraclejdk11

matrix:
  include:
    - rvm: 2.7.4
      before_script: psql -c 'create database delayed_job_test;' -U postgres
    

sudo: false
